### ISSUE TITLE
improve ACCESS login instructions for XSEDE users transferring identity to ACESS for the first time.

### ISSUE THREAD

**Issue by jodischneider** [cilogon/access-identity#21]
Improve ACCESS login instructions for XSEDE users transferring identity to ACESS for the first time. The current process does not make obvious what a new user should do, despite multiple places requesting that users NOT create a new account. Here are some starting points for thinking about how to improve login instructions, or the problems users might face:

From https://identity.access-ci.org/new-user
* Provide clear instructions of where/how to login if you already have an XSEDE or ACCESS account. Top of page where you link to password reset/username lookup is the most obvious place for that
It appears that this should be something related to 
https://idp.access-ci.org/idp/ and/or cilogon.

From https://identity.access-ci.org
* “Select the “ACCESS CI (XSEDE)” identity provider to log on using your XSEDE account." is not clear. Provide clear instructions of where/how to login. In particular, add a link here.

From https://allocations.access-ci.org
"Create account" should not be the first step if you want people to use an existing account

https://identity.access-ci.org/user-not-registered
"Error: User Not Registered with ACCESS"
https://registry.access-ci.org/registry/
Try to create a more helpful message that suggests XSEDE users have just a few new steps to follow.

On the ultimate login
https://idp.access-ci.org/idp/profile/SAML2/Redirect/SSO?execution=e1s1
increase the visibility of XSEDE - asking for an XSEDE account at the BOTTOM in small print is confusing for those who are using ACCESS for the first time.

**Comment by jbasney** [comment]
Thanks for the detailed feedback. Much appreciated! We'll work on it...

**Comment by terrencegf** [comment]
Many of these great suggestions have been incorporated into the latest web pages at https://operations.access-ci.org/identity . https://registry.access-ci.org/ has been operational for nearly 1-1/2 years, and it's rare for an XSEDE user to log on for the first time. So, I'm closing this issue.
