### ISSUE TITLE
Review "submit a ticket" link in registry.access-ci.org email notifications

### ISSUE THREAD

**Issue by jbasney** [cilogon/access-identity#26]
Review the registry.access-ci.org email notifications for links to https://support.access-ci.org/open-a-ticket (requires authentication) versus https://support.access-ci.org/form/account-assistance (does not require authentication).

For example, the "Your password has been changed" notification currently points to https://support.access-ci.org/open-a-ticket to report a security issue, but if an attacker just changed the user's password, they won't be able to log in to submit a ticket there.

**Comment by terrencegf** [comment]
I updated all of the ACCESS Message Templates to something like this:

```
If you did not intend to generate a new ACCESS ID or if you suspect 
a security incident, please contact the ACCESS Help Desk immediately 
at support@access-ci.atlassian.net .
```

This eliminates hyperlinks in emails from https://registry.access-ci.org/ and allows the user to create a Jira Help Ticket using their favorite email client. I have seen at least one user create a ticket using the support@access-ci.atlassian.net address, so I know it works.
