### ISSUE TITLE
Remove "Other" from organization list

### ISSUE THREAD

**Issue by jbasney** [cilogon/access-identity#27]
Update the user registration page to tell users to select their organization from the list and if it is not there, to submit a ticket at TBD to get their org added. Don't give them the option to select "Other" and proceed with the registration.

**Comment by jbasney** [comment]
https://support.access-ci.org/form/organization-request is the form we should use to get the org added.

**Comment by jbasney** [comment]
I'm told the https://support.access-ci.org/form/organization-request form is not working. We're checking with the ACCESS support team about it.

**Comment by terrencegf** [comment]
The form is now submitting new org requests to the [ACCESS ticketing system](https://access-ci.atlassian.net/jira/servicedesk/projects/ATS/queues/custom/7/ATS-2568) (link requires authentication). However, it is unclear who, if anyone, is handling those tickets.
