### ISSUE TITLE
Unable to ssh into Expanse with my credentials

### ISSUE THREAD

**Issue by eyulaeva1** [cilogon/access-identity#30]
Access UI is so unfriendly. I  am spending an enormous amount of time getting to your real "help desk"  not Q&A -- will make sure to escalate this issue to your NSF  program officer. 
There are so many issues with your platform -- don't even know where to start.
Right now, the most pressing one -- where do I get help with the  "ssh-ing"  into Expanse? Seems like the transfer to Access ruined my credentials there

**Comment by jbasney** [comment]
Please contact consult@sdsc.edu for help with SSH access to Expanse.
