### ISSUE TITLE
Send email to user upon creation of a new ACCESS ID

### ISSUE THREAD

**Issue by terrencegf** [cilogon/access-identity#36]
From Andrew Pasquale:

In Support, we have been discussing the possibilities for sharing information about ACCESS with people when they first create an account with ACCESS. An initial communication could contain information about the next steps, how to request an allocation, how to determine which resource to exchange credits for, and what kinds of support are available. It would be important to get input from all the ACCESS groups for the content of this communication. Welcome emails are a standard process after creating new accounts for most organizations and are a good way to provide useful information to people.

**Comment by jbasney** [comment]
Note that COmanage redirects users to https://operations.access-ci.org/identity/enrollment-complete when they first create an account, so this information could be added to that page.

**Comment by terrencegf** [comment]
I notified Andrew that there is already an email sent to the user upon successful creation of a new ACCESS account:

```
Hello Terrence Fleury,

Your new ACCESS ID/username is tfleury4.

If you did not intend to generate a new ACCESS ID or if you suspect a security incident, please contact the ACCESS Help Desk immediately at support@access-ci.atlassian.net .

Thank you,
ACCESS Registry Team
```

Andrew will work with his team to tweak this email as they like (even though adding links may cause the user's university to spamify the email).
