### ISSUE TITLE
Update styling for links on registry.access-ci.org pages

### ISSUE THREAD

**Issue by jbasney** [cilogon/access-identity#9]
For example, on the self-service password reset page, "click here" doesn't look like a link (i.e., it's not underlined or otherwise styled differently from the surrounding text), until you hover over it with the mouse.

**Comment by skoranda** [comment]
@jbasney Please review https://registry.access-ci.org/registry/krb_authenticator/krbs/ssr/authenticatorid:1 and close this issue if you are satisfied. If not, please leave detailed input on what CSS changes are necessary. Thanks.

**Comment by jbasney** [comment]
thanks @skoranda !
